fix: #7 fix workflow

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -25,31 +25,70 @@ jobs:
           echo "Latest 'test-' tag: $latest_test_tag"
           echo "LATEST_TEST_TAG=$latest_test_tag" >> $GITHUB_ENV
 
-      # Step 3: Create new tag and push it to remote
-      - name: Create new tag
+      - name: Generate tag
+        id: release_tag
         run: |
-          git tag test-${{ github.event.inputs.version }}
-          git push origin test-${{ github.event.inputs.version }}
-          echo "CREATE_TAG=test-${{ github.event.inputs.version }}" >> $GITHUB_ENV
+          echo "release_tag=test-${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
+
+      # Step 3: Create new tag and push it to remote
+      # - name: Create new tag
+      #   run: |
+      #     git tag test-${{ github.event.inputs.version }}
+      #     git push origin test-${{ github.event.inputs.version }}
+      #     echo "CREATE_TAG=test-${{ github.event.inputs.version }}" >> $GITHUB_ENV
 
       # Step 4: Generate release notes using GitHub API and configuration file
       - name: Generate release notes
+        id: changes
         run: |
-          release_notes=$(curl -s -X POST https://api.github.com/repos/${{ github.repository }}/releases/generate-release-notes \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+          echo "changes=$(
+          curl -X POST \
+            -H 'Accept: application/vnd.github.v3+json' \
+            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
+            https://api.github.com/repos/${{ github.repository }}/releases/generate-notes \
             -d '{
-                  "tag_name": "'test-${{ github.event.inputs.version }}'",
-                  "previous_tag_name": "'${{ env.LATEST_TEST_TAG }}'",
-                  "configuration_file_path": ".github/configs/release-notes.yml"
-                }')
-          echo "$release_notes"
-          echo "$release_notes" > release_notes.md
+              "tag_name": "${{ steps.release_tag.outputs.release_tag }}",
+              "previous_tag_name": "${{ env.LATEST_TEST_TAG }}",
+              "configuration_file_path": ".github/configs/release-notes.yml",
+              "target_commitish": "main"
+            }' | jq .body
+          )" >> $GITHUB_OUTPUT
+
+      # Step 5: リリースノートの本文を作成する
+      - name: Create release note body
+        id: release_note_body
+        run: |
+          echo "release_note_body=$(echo \
+            ${{ steps.changes.outputs.changes }} \
+            | sed 's/\\"//g' | sed 's/["“]//g')" >> $GITHUB_OUTPUT
 
       # Step 4: Create GitHub Release with generated release notes
-      - name: Create GitHub Release
-        uses: softprops/action-gh-release@v1
-        with:
-          tag_name: ${{ env.CREATE_TAG }}
-          files: release_notes.md
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Create GitHub Release
+      #   uses: softprops/action-gh-release@v1
+      #   with:
+      #     tag_name: ${{ env.CREATE_TAG }}
+      #     files: release_notes.md
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Create Release
+        run: |
+          response=$(curl -X POST \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -d "{ \
+              \"tag_name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
+              \"target_commitish\": \"main\", \
+              \"name\": \"${{ steps.release_tag.outputs.release_tag }}\", \
+              \"body\": \"${{ steps.release_note_body.outputs.release_note_body }}\" \
+            }" \
+            -w "%{http_code}" \
+            -o response_body.txt \
+            https://api.github.com/repos/${{ github.repository }}/releases)
+            status_code=$(tail -n1 <<< "$response")
+            echo "Status Code: $status_code"
+            body=$(cat response_body.txt)
+            echo "Response Body: $body"
+            if [ $status_code -ne 201 ]; then
+              echo "Failed to create release"
+              exit 1
+            fi
